# Generated by Django 2.2.2 on 2019-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20190617_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='branch',
            field=models.CharField(default='', max_length=30),
        ),
    ]
